In [2]:
import torch
import torch.nn as nn


In [3]:
model1 = nn.Linear(10, 5)
pam1 = model1.parameters()
tensor_pam1 = [param.data for param in model1.parameters()]
tensor_pam1

[tensor([[ 0.0119, -0.1868,  0.0763, -0.1308, -0.0463,  0.0796, -0.2051, -0.1638,
          -0.3126,  0.0237],
         [-0.0395,  0.0303, -0.1330,  0.0370,  0.1246, -0.2403,  0.1316,  0.1017,
           0.0576, -0.0534],
         [ 0.3136, -0.0047, -0.1855, -0.0581, -0.0355, -0.0879,  0.2310, -0.2846,
           0.2583, -0.0170],
         [-0.2453, -0.0901, -0.0159,  0.0618,  0.2856,  0.1609,  0.1372, -0.1462,
          -0.2530, -0.2331],
         [-0.0277,  0.2110, -0.2563,  0.2081, -0.0038, -0.2261,  0.1924,  0.0676,
          -0.0402,  0.1631]]),
 tensor([ 0.1209,  0.1190,  0.2836, -0.0420,  0.1115])]

In [4]:
params = [param.data.flatten() for param in model1.parameters()]
flatten_tensor = torch.cat(params)
flatten_tensor.shape

torch.Size([55])

In [5]:
new_model = nn.Linear(10, 5)
tensor_pam2 = [param.data for param in new_model.parameters()]
requires_grad_list = [param.requires_grad for param in new_model.parameters()]
tensor_pam2

[tensor([[-0.3062, -0.3013, -0.0992, -0.0722, -0.0285,  0.1003,  0.0422,  0.1166,
          -0.1562,  0.0765],
         [-0.2228,  0.2648,  0.2487,  0.0376,  0.2403, -0.2967, -0.0148, -0.2660,
          -0.2071,  0.0090],
         [ 0.0851,  0.2822,  0.2426, -0.0332, -0.2193,  0.2510,  0.2996, -0.2854,
          -0.2845,  0.1329],
         [ 0.1962,  0.2307,  0.2005, -0.1708, -0.1350,  0.0151, -0.0410, -0.0270,
           0.2319,  0.0942],
         [ 0.1967, -0.0381, -0.0976, -0.0904,  0.2985, -0.0363, -0.2055, -0.1301,
          -0.1658, -0.0217]]),
 tensor([0.1718, 0.0760, 0.1575, 0.3010, 0.0899])]

In [6]:
param_index = 0
for param, requires_grad in zip(new_model.parameters(), requires_grad_list):
    param_shape = param.data.shape
    param.data = flatten_tensor[param_index:param_index+param.numel()].reshape(param_shape)
    param.requires_grad = requires_grad
    param_index += param.numel()
tensor_pam2 = [param.data for param in new_model.parameters()]
tensor_pam2

[tensor([[ 0.0119, -0.1868,  0.0763, -0.1308, -0.0463,  0.0796, -0.2051, -0.1638,
          -0.3126,  0.0237],
         [-0.0395,  0.0303, -0.1330,  0.0370,  0.1246, -0.2403,  0.1316,  0.1017,
           0.0576, -0.0534],
         [ 0.3136, -0.0047, -0.1855, -0.0581, -0.0355, -0.0879,  0.2310, -0.2846,
           0.2583, -0.0170],
         [-0.2453, -0.0901, -0.0159,  0.0618,  0.2856,  0.1609,  0.1372, -0.1462,
          -0.2530, -0.2331],
         [-0.0277,  0.2110, -0.2563,  0.2081, -0.0038, -0.2261,  0.1924,  0.0676,
          -0.0402,  0.1631]]),
 tensor([ 0.1209,  0.1190,  0.2836, -0.0420,  0.1115])]

In [7]:
list(model1.parameters())

[Parameter containing:
 tensor([[ 0.0119, -0.1868,  0.0763, -0.1308, -0.0463,  0.0796, -0.2051, -0.1638,
          -0.3126,  0.0237],
         [-0.0395,  0.0303, -0.1330,  0.0370,  0.1246, -0.2403,  0.1316,  0.1017,
           0.0576, -0.0534],
         [ 0.3136, -0.0047, -0.1855, -0.0581, -0.0355, -0.0879,  0.2310, -0.2846,
           0.2583, -0.0170],
         [-0.2453, -0.0901, -0.0159,  0.0618,  0.2856,  0.1609,  0.1372, -0.1462,
          -0.2530, -0.2331],
         [-0.0277,  0.2110, -0.2563,  0.2081, -0.0038, -0.2261,  0.1924,  0.0676,
          -0.0402,  0.1631]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1209,  0.1190,  0.2836, -0.0420,  0.1115], requires_grad=True)]

In [8]:
list(new_model.parameters())

[Parameter containing:
 tensor([[ 0.0119, -0.1868,  0.0763, -0.1308, -0.0463,  0.0796, -0.2051, -0.1638,
          -0.3126,  0.0237],
         [-0.0395,  0.0303, -0.1330,  0.0370,  0.1246, -0.2403,  0.1316,  0.1017,
           0.0576, -0.0534],
         [ 0.3136, -0.0047, -0.1855, -0.0581, -0.0355, -0.0879,  0.2310, -0.2846,
           0.2583, -0.0170],
         [-0.2453, -0.0901, -0.0159,  0.0618,  0.2856,  0.1609,  0.1372, -0.1462,
          -0.2530, -0.2331],
         [-0.0277,  0.2110, -0.2563,  0.2081, -0.0038, -0.2261,  0.1924,  0.0676,
          -0.0402,  0.1631]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1209,  0.1190,  0.2836, -0.0420,  0.1115], requires_grad=True)]