In [11]:
import torch
import torch.nn as nn

In [12]:
model1 = nn.Linear(10, 5)
params1 = [param.data.flatten() for param in model1.parameters()]
flatten_params1 = torch.cat(params1)
flatten_params1

tensor([-0.2504, -0.1686, -0.2071,  0.2045,  0.2483,  0.0239,  0.1566, -0.2015,
        -0.3014, -0.0883,  0.2227,  0.0016, -0.0966, -0.2528,  0.3083,  0.1203,
        -0.0627,  0.1063, -0.2268,  0.2454, -0.1446, -0.1262,  0.1783, -0.1334,
        -0.0655,  0.1614,  0.1577, -0.0065, -0.0947, -0.1418,  0.0944, -0.2842,
        -0.2788, -0.0055, -0.0337, -0.0265,  0.1177,  0.0031, -0.0521,  0.1755,
         0.2641, -0.0791,  0.2433, -0.2199,  0.1729, -0.2985,  0.0735, -0.2506,
         0.1545, -0.0698, -0.0310,  0.1281, -0.0304, -0.0591,  0.2972])

In [13]:
model2 = nn.Linear(10, 5)
params2 = [param.data.flatten() for param in model2.parameters()]
flatten_params2 = torch.cat(params2)
flatten_params2

tensor([-0.0134,  0.2111,  0.1438,  0.2480, -0.1816, -0.0566,  0.2278,  0.0869,
         0.3139,  0.2704,  0.2540, -0.1433, -0.1090, -0.2690,  0.0347,  0.2536,
         0.2281, -0.2991, -0.2889, -0.1275,  0.3100,  0.1889, -0.2422, -0.1160,
         0.0008,  0.0628, -0.2079,  0.2694, -0.2042,  0.0742, -0.2024, -0.0093,
        -0.0179,  0.2016,  0.3006,  0.1066,  0.1678,  0.3064, -0.2511,  0.1133,
         0.2168, -0.1233, -0.2181, -0.0791, -0.1739, -0.1208,  0.2022, -0.1801,
         0.0129, -0.1719, -0.2290, -0.0737,  0.1259, -0.1496, -0.1974])

In [14]:
gather = [flatten_params1,flatten_params2]
gather = torch.stack(gather)
mean_gathered_params = torch.mean(gather, dim=0)
gather

tensor([[-0.2504, -0.1686, -0.2071,  0.2045,  0.2483,  0.0239,  0.1566, -0.2015,
         -0.3014, -0.0883,  0.2227,  0.0016, -0.0966, -0.2528,  0.3083,  0.1203,
         -0.0627,  0.1063, -0.2268,  0.2454, -0.1446, -0.1262,  0.1783, -0.1334,
         -0.0655,  0.1614,  0.1577, -0.0065, -0.0947, -0.1418,  0.0944, -0.2842,
         -0.2788, -0.0055, -0.0337, -0.0265,  0.1177,  0.0031, -0.0521,  0.1755,
          0.2641, -0.0791,  0.2433, -0.2199,  0.1729, -0.2985,  0.0735, -0.2506,
          0.1545, -0.0698, -0.0310,  0.1281, -0.0304, -0.0591,  0.2972],
        [-0.0134,  0.2111,  0.1438,  0.2480, -0.1816, -0.0566,  0.2278,  0.0869,
          0.3139,  0.2704,  0.2540, -0.1433, -0.1090, -0.2690,  0.0347,  0.2536,
          0.2281, -0.2991, -0.2889, -0.1275,  0.3100,  0.1889, -0.2422, -0.1160,
          0.0008,  0.0628, -0.2079,  0.2694, -0.2042,  0.0742, -0.2024, -0.0093,
         -0.0179,  0.2016,  0.3006,  0.1066,  0.1678,  0.3064, -0.2511,  0.1133,
          0.2168, -0.1233, -0.2181, 

In [15]:
mean_gathered_params

tensor([-0.1319,  0.0213, -0.0317,  0.2263,  0.0334, -0.0164,  0.1922, -0.0573,
         0.0063,  0.0910,  0.2384, -0.0709, -0.1028, -0.2609,  0.1715,  0.1870,
         0.0827, -0.0964, -0.2578,  0.0590,  0.0827,  0.0314, -0.0319, -0.1247,
        -0.0323,  0.1121, -0.0251,  0.1314, -0.1495, -0.0338, -0.0540, -0.1467,
        -0.1483,  0.0981,  0.1335,  0.0401,  0.1427,  0.1547, -0.1516,  0.1444,
         0.2404, -0.1012,  0.0126, -0.1495, -0.0005, -0.2097,  0.1378, -0.2154,
         0.0837, -0.1208, -0.1300,  0.0272,  0.0478, -0.1044,  0.0499])